# Generated by Django 5.1.3 on 2024-11-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
